// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_xuE71N78uWKIN_fp2P4eOkukIiZuHE',
    appId: '1:951600175900:web:e0aca0e9310d81f0fa38d9',
    messagingSenderId: '951600175900',
    projectId: 'guideme-1234',
    authDomain: 'guideme-1234.firebaseapp.com',
    storageBucket: 'guideme-1234.appspot.com',
    measurementId: 'G-77KPXJQBNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2OXYXjtADzVovHjkKeRm95BVrNEValjw',
    appId: '1:951600175900:android:da05725c4d3d78b7fa38d9',
    messagingSenderId: '951600175900',
    projectId: 'guideme-1234',
    storageBucket: 'guideme-1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2c77E-hwLTFciATjb0bgPlgKuwVNHWM',
    appId: '1:951600175900:ios:b55c45a5d9652e8cfa38d9',
    messagingSenderId: '951600175900',
    projectId: 'guideme-1234',
    storageBucket: 'guideme-1234.appspot.com',
    iosBundleId: 'com.example.guideme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh2c77E-hwLTFciATjb0bgPlgKuwVNHWM',
    appId: '1:951600175900:ios:b55c45a5d9652e8cfa38d9',
    messagingSenderId: '951600175900',
    projectId: 'guideme-1234',
    storageBucket: 'guideme-1234.appspot.com',
    iosBundleId: 'com.example.guideme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1_xuE71N78uWKIN_fp2P4eOkukIiZuHE',
    appId: '1:951600175900:web:745f935d0caf58c0fa38d9',
    messagingSenderId: '951600175900',
    projectId: 'guideme-1234',
    authDomain: 'guideme-1234.firebaseapp.com',
    storageBucket: 'guideme-1234.appspot.com',
    measurementId: 'G-BCHDM4SSQ3',
  );
}
